sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 10.16.0
branches:
  only:
    - master
    - develop
    - rewrite
notifications:
  email: false
script:
  - yarn run validate
after_success:
  - yarn run prod
